name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 'Build:dockerimage'
      uses: docker/build-push-action@v1
      with:
        registry: ghcr.io
        username: "vlladdrakk"
        password: ${{ secrets.PAC }}
        repository: vlladdrakk/pod-proxy
        tags: latest

